[package]
name = "plugin-runtime-containerd"
version = "0.1.0"
authors = ["Marek Counts <mcounts@suse.com>"]
edition = "2018"

[lib]
name = "pluginruntimecontainerd"
crate-type = ["cdylib"]

[dependencies]
